version: '3.9'

services:
  app:
    build:
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    env_file:
      - ./app/.env
    depends_on:
      database:
        condition: service_healthy

  database:
    image: postgres:13
    restart: always
    env_file:
      - ./app/db.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./app/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local
